---
title: "VitalRates_stats"
author: "Caroline Rodriguez"
date: "11/11/2020"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(plyr)
```


#Set up
```{r}
setwd("/Users/c-rod/Documents/R_data/VitalRates/")
#load in .rdata file
load(file = "/Users/c-rod/Documents/R_data/VitalRates/Patch_And_Colony_Data_20201103.rdata")
#View both tables saved in the .rdata
View(ColonyLevel)
View(PatchLevel)

```


#Subset by Site
Going to use ColonyLevel data to avoid all the fission/fusion confusion
```{r}
MAISIOK01 <- subset(ColonyLevel, Site=="MAI_SIO_K01")
View(MAISIOK01)

KUROCC010 <- subset(ColonyLevel, Site=="KUR_OCC_010")
View(KUROCC010)

PHROCC016 <- subset(ColonyLevel, Site=="PHR_OCC_016")
View(PHROCC016)

```



#Plot by Colony Level (growth, shrink, mort, recruit)
```{r}
#change this basepath to your working directory on your computer
basepath="/Users/c-rod/Documents/R_data/VitalRates/"

#the shape palette is messed up because it can deal w/ a max of 6 discrete values and we have 53 b/c all the fissiongrowthfusion, growthfissionfission, etc. Instead used the TransitionTypeSimple (growth,shrink,mort, recr)
T0T1 = ggplot(data = MAISIOK01, aes(x=StartingSize, y=EndingSize,color=TransitionTypeSimple,shape=TransitionTypeSimple)) + 
  geom_point() + geom_abline(slope = 1)+
  scale_x_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+ #log transform x axis
  scale_y_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+
  scale_shape_manual(values=0:4)+
  facet_grid(c("Genus_Code","Site"))+theme_bw()+ #facet_grid separates by Genus Code (makes 3 verticle plots) and Site (makes horizontal plots)
  xlab("Colony Size at Time T (cm^2)") + ylab("Colony Size at Time T+1 (cm^2)")
T0T1
scale=3
ggsave(filename = paste0(basepath,"Figures/TransitionTypeT0T1ByGenus_MAIK01.png"),
       plot=T0T1,width=6*scale,height=scale*3)

#same plot as above but adds lines
T0T1_lin = ggplot(data = MAISIOK01, aes(x=StartingSize, y=EndingSize,color=TransitionTypeSimple,shape=TransitionTypeSimple,group=ColonyID)) + 
  geom_point() + 
  geom_line(alpha=.15,color="black")+
  geom_abline(slope = 1)+
  scale_x_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+ #log transform x axis
  scale_y_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+
  scale_shape_manual(values=0:4)+
  facet_grid(c("Genus_Code","Site"),scales="free")+theme_bw()+
  xlab("Colony Size at Time T (cm^2)") + ylab("Colony Size at Time T+1 (cm^2)")
T0T1_lin

#################################
#Kure
T0T1K = ggplot(data = KUROCC010, aes(x=StartingSize, y=EndingSize,color=TransitionTypeSimple,shape=TransitionTypeSimple)) + 
  geom_point() + geom_abline(slope = 1)+
  scale_x_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+ #log transform x axis
  scale_y_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+
  scale_shape_manual(values=0:4)+
  facet_grid(c("Genus_Code","Site"))+theme_bw()+ #facet_grid separates by Genus Code (makes 3 verticle plots) and Site (makes horizontal plots)
  xlab("Colony Size at Time T (cm^2)") + ylab("Colony Size at Time T+1 (cm^2)")
T0T1K
#ggsave(filename = paste0(basepath,"Figures/TransitionTypeT0T1ByGenus_KUR.png"),plot=T0T1K,width=6*scale,height=scale*3)

#################################
#PHR
T0T1P = ggplot(data = PHROCC016, aes(x=StartingSize, y=EndingSize,color=TransitionTypeSimple,shape=TransitionTypeSimple)) + 
  geom_point() + geom_abline(slope = 1)+
  scale_x_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+ #log transform x axis
  scale_y_sqrt(breaks=c(10,50,100,250,500,1000,2000),limits=c(0,400))+
  scale_shape_manual(values=0:4)+
  facet_grid(c("Genus_Code","Site"))+theme_bw()+ #facet_grid separates by Genus Code (makes 3 verticle plots) and Site (makes horizontal plots)
  xlab("Colony Size at Time T (cm^2)") + ylab("Colony Size at Time T+1 (cm^2)")
T0T1P
#ggsave(filename = paste0(basepath,"Figures/TransitionTypeT0T1ByGenus_PHR.png"),plot=T0T1P,width=6*scale,height=scale*3)


```
#Plot by Colony Level (growth, shrink, mort, recruit) and Transition
```{r}

```






